sheep:
  enabled: true
  chance: 0.1
cow:
  enabled: true
  chance: 0.1
pig:
  enabled: true
  chance: 0.1
rabbit:
  enabled: true
  chance: 0.4
panda:
  enabled: true
  chance: 0.1
dog:
  enabled: true
  chance: 0.1
cat:
  enabled: true
  chance: 0.1
horse:
  enabled: true
  chance: 0.1
llama:
  enabled: true
  chance: 0.1
fox:
  enabled: true
  chance: 0.1
